server:
  env_name: ${APP_ENV:azopenai}

llm:
  mode: azopenai

embedding:
  mode: azopenai

azopenai:
  api_key: ${Key}
  azure_endpoint: https://lh-openai-01.openai.azure.com/
  embedding_deployment_name: text-embedding-ada-002
  llm_deployment_name: gpt-4
  api_version: "2023-05-15"
  embedding_model: text-embedding-ada-002
  llm_model: gpt-4